public without sharing class OPAConstants {


// Interface settings   
    public static final String VERSION = '12.2.1';
    public static final String SERVICE_URI = '/rulesSOAP/v2/rules/';
    public static final String SOAPACTION = '"http://oracle.com/determinations/server/12.2.1/rulebase/types/Assess"'; 

// Picklist values
    public static final String TARIF_GENERAL = 'Tarif general';
    public static final String TARIF_REDUIT = 'Tarif reduit';

    public static final String TYPE_TEXTE = '1';    
    public static final String TYPE_BOOLEEN = '3';    
    public static final String TYPE_DATE = '4';    
    public static final String TYPE_NOMBRE = '5';
    public static final String TYPE_DEVISE = '6';

    public static final String TARGET_STANDARD = 'Standard';
    public static final String TARGET_SPACE = 'Espace de diffusion';
    public static final String TARGET_MOYEN = 'Moyen de diffusion';

    public static final String COMPANY_SACEM = 'SACEM';
    public static final String COMPANY_SPRE = 'SPRE';

    public static final String OUTCOME_TARIF = '1';
    public static final String OUTCOME_REPARTITION = '2';

    public static final String BOOLEAN_YES = '1';
    public static final String BOOLEAN_NO = '2';

    public static final String ACTIVITY_AREA_CASINO = 'CASINO';

// JSON response values
    public static final String ENTITY_TYPE_GLOBAL = 'global';
    public static final String ENTITY_TYPE_SPACE = 'ESPACE_SONO';
    public static final String ENTITY_TYPE_WAY_DIFFUSION = 'MOYEN_DIFF';

}